### ISSUE TITLE
Issue downloading images from Plex

### ISSUE THREAD

**Issue by fieccle01** [gssariev/maintainerr-overlay-helperr#15]
Hi,

I am seeing the following issue when the tool tries to download the original images. This becomes a blocker for the whole process:

Downloading poster from: http://plex:32400/library/metadata/76201/thumb?X-Plex-Token=<token> to: /images/originals/76201.jpg
WARNING: File at /images/originals/76201.jpg is not a valid image. Error: Exception calling "FromFile" with "1" argument(s): "The type initializer for 'Gdip' threw an exception."
WARNING: Downloaded file at /images/originals/76201.jpg is not a valid image. Deleting file.
WARNING: Failed to download poster from http://plex:32400/library/metadata/76201/thumb?X-Plex-Token=<token> to /images/originals/76201.jpg. Error: Invalid poster file format detected.
WARNING: Failed to process Plex ID: 76201. Error: Invalid poster file format detected.

The source image format is jpg.

Plex version: 1.41.5.9522
Docker tag: Latest

Let me know if there is any more information required.

Thanks

**Comment by corvus2606** [comment]
I'm getting the same error for all posters in my plex server

**Comment by corvus2606** [comment]
> Working on a fix. Could you share what type of image gave this error? Is it a .webp or something else?

It's all .jpg so far as i can see, no references to .webp in the logs.

Please see an example from my logs: 

`WARNING: File at /images/originals/78255.jpg is not a valid image. Error: Exception calling "FromFile" with "1" argument(s): "The type initializer for 'Gdip' threw an exception."
WARNING: Downloaded file at /images/originals/78255.jpg is not a valid image. Deleting file.
WARNING: Failed to download poster from http://192.168.0.58:32400/library/metadata/78255/thumb?X-Plex-Token=**************** to /images/originals/78255.jpg. Error: Invalid poster file format detected.
WARNING: Failed to process Plex ID: 78255. Error: Invalid poster file format detected.`

**Comment by gssariev** [comment]
@corvus2606 

If you have the chance, you can try out the develop image available at **gsariev/maintainerr-overlay-helperr:develop** . As it is based on v1.0.2 the following variables have not yet been implemented: BACK_WIDTH, BACK_HEIGHT, DATE_FORMAT, ENABLE_DAY_SUFFIX, ENABLE_UPPERCASE, LANGUAGE

Small changes based on feedback:
MAINTAINERR_URL: "http://192.168.0.139:6246/" - removed the trailing /api/ endpoint from the variable, just add your maintainerr IP and port. You can still use the docker-compose for **v1.0.3** as those variables will be implemented as soon as the core overlay functionality works. I've tested the container running on Windows, macOS and Unraid, and things seem to be working as expected.

Let me know if the issue is resolved :)

**Comment by fieccle01** [comment]
I will try this as well tonight.

**Comment by corvus2606** [comment]
Hi @gssariev 

Just tested and all images downloaded 👍 .  I'm seeing some different errors from magick, but I assume this is related to the version?

`2025-04-29T19:48:20.536872344Z Added to newState: Plex ID = 82991, State = true
2025-04-29T19:48:20.538279508Z Original poster already exists for Plex ID: 82991.
2025-04-29T19:48:20.570488624Z Item 82991 has a formatted date: Mar 3rd
2025-04-29T19:48:20.710422822Z magick: unable to read font `/fonts' @ warning/annotate.c/RenderType/949.
2025-04-29T19:48:20.710467319Z magick: unable to read font `/fonts' @ error/annotate.c/RenderFreetype/1396.
2025-04-29T19:48:20.710469469Z magick: no images defined `/images/temp/label.png' @ error/convert.c/ConvertImageCommand/3229.
2025-04-29T19:48:20.722352791Z magick: unable to open image `/images/temp/label.png': No such file or directory @ error/blob.c/OpenBlob/2924.
2025-04-29T19:48:20.722392419Z magick: no images defined `/images/temp/label.png' @ error/convert.c/ConvertImageCommand/3229.
2025-04-29T19:48:20.732842115Z magick: unable to open image `/images/temp/label.png': No such file or directory @ error/blob.c/OpenBlob/2924.
2025-04-29T19:48:20.732865827Z magick: no images defined `info:' @ error/convert.c/ConvertImageCommand/3229.
2025-04-29T19:48:20.743994972Z magick: unable to open image `/images/temp/label.png': No such file or directory @ error/blob.c/OpenBlob/2924.
2025-04-29T19:48:20.744019740Z magick: image sequence is required `+clone' @ error/convert.c/ConvertImageCommand/948.
2025-04-29T19:48:20.753303312Z magick: unable to open image `/images/temp/label.png': No such file or directory @ error/blob.c/OpenBlob/2924.
2025-04-29T19:48:20.753330986Z magick: image sequence is required `+clone' @ error/convert.c/ConvertImageCommand/948.
2025-04-29T19:48:20.885116370Z magick: unable to open image `/images/temp/shadowed_label.png': No such file or directory @ error/blob.c/OpenBlob/2924.
2025-04-29T19:48:20.885142684Z magick: image sequence is required `-composite' @ error/mogrify.c/MogrifyImageList/8003.
2025-04-29T19:48:20.885144695Z magick: no images defined `/images/temp/82991.jpg' @ error/convert.c/ConvertImageCommand/3229.
2025-04-29T19:48:20.914276346Z 
2025-04-29T19:48:20.924508381Z Deleted temporary file: /images/temp/82991.jpg`

**Comment by gssariev** [comment]
> Hi @gssariev 
> 
> Just tested and all images downloaded 👍 .  I'm seeing some different errors from magick, but I assume this is related to the version?
> 
> ```
> 2025-04-29T19:48:20.536872344Z Added to newState: Plex ID = 82991, State = true
> 2025-04-29T19:48:20.538279508Z Original poster already exists for Plex ID: 82991.
> 2025-04-29T19:48:20.570488624Z Item 82991 has a formatted date: Mar 3rd
> 2025-04-29T19:48:20.710422822Z magick: unable to read font `/fonts' @ warning/annotate.c/RenderType/949.
> 2025-04-29T19:48:20.710467319Z magick: unable to read font `/fonts' @ error/annotate.c/RenderFreetype/1396.
> 2025-04-29T19:48:20.710469469Z magick: no images defined `/images/temp/label.png' @ error/convert.c/ConvertImageCommand/3229.
> 2025-04-29T19:48:20.722352791Z magick: unable to open image `/images/temp/label.png': No such file or directory @ error/blob.c/OpenBlob/2924.
> 2025-04-29T19:48:20.722392419Z magick: no images defined `/images/temp/label.png' @ error/convert.c/ConvertImageCommand/3229.
> 2025-04-29T19:48:20.732842115Z magick: unable to open image `/images/temp/label.png': No such file or directory @ error/blob.c/OpenBlob/2924.
> 2025-04-29T19:48:20.732865827Z magick: no images defined `info:' @ error/convert.c/ConvertImageCommand/3229.
> 2025-04-29T19:48:20.743994972Z magick: unable to open image `/images/temp/label.png': No such file or directory @ error/blob.c/OpenBlob/2924.
> 2025-04-29T19:48:20.744019740Z magick: image sequence is required `+clone' @ error/convert.c/ConvertImageCommand/948.
> 2025-04-29T19:48:20.753303312Z magick: unable to open image `/images/temp/label.png': No such file or directory @ error/blob.c/OpenBlob/2924.
> 2025-04-29T19:48:20.753330986Z magick: image sequence is required `+clone' @ error/convert.c/ConvertImageCommand/948.
> 2025-04-29T19:48:20.885116370Z magick: unable to open image `/images/temp/shadowed_label.png': No such file or directory @ error/blob.c/OpenBlob/2924.
> 2025-04-29T19:48:20.885142684Z magick: image sequence is required `-composite' @ error/mogrify.c/MogrifyImageList/8003.
> 2025-04-29T19:48:20.885144695Z magick: no images defined `/images/temp/82991.jpg' @ error/convert.c/ConvertImageCommand/3229.
> 2025-04-29T19:48:20.914276346Z 
> 2025-04-29T19:48:20.924508381Z Deleted temporary file: /images/temp/82991.jpg
> ```

Would you mind sharing your how you've set up your docker compose? (Redacting API key, Plex token)

**Comment by corvus2606** [comment]
> > Hi [@gssariev](https://github.com/gssariev)
> > Just tested and all images downloaded 👍 .  I'm seeing some different errors from magick, but I assume this is related to the version?
> > ```
> > 2025-04-29T19:48:20.536872344Z Added to newState: Plex ID = 82991, State = true
> > 2025-04-29T19:48:20.538279508Z Original poster already exists for Plex ID: 82991.
> > 2025-04-29T19:48:20.570488624Z Item 82991 has a formatted date: Mar 3rd
> > 2025-04-29T19:48:20.710422822Z magick: unable to read font `/fonts' @ warning/annotate.c/RenderType/949.
> > 2025-04-29T19:48:20.710467319Z magick: unable to read font `/fonts' @ error/annotate.c/RenderFreetype/1396.
> > 2025-04-29T19:48:20.710469469Z magick: no images defined `/images/temp/label.png' @ error/convert.c/ConvertImageCommand/3229.
> > 2025-04-29T19:48:20.722352791Z magick: unable to open image `/images/temp/label.png': No such file or directory @ error/blob.c/OpenBlob/2924.
> > 2025-04-29T19:48:20.722392419Z magick: no images defined `/images/temp/label.png' @ error/convert.c/ConvertImageCommand/3229.
> > 2025-04-29T19:48:20.732842115Z magick: unable to open image `/images/temp/label.png': No such file or directory @ error/blob.c/OpenBlob/2924.
> > 2025-04-29T19:48:20.732865827Z magick: no images defined `info:' @ error/convert.c/ConvertImageCommand/3229.
> > 2025-04-29T19:48:20.743994972Z magick: unable to open image `/images/temp/label.png': No such file or directory @ error/blob.c/OpenBlob/2924.
> > 2025-04-29T19:48:20.744019740Z magick: image sequence is required `+clone' @ error/convert.c/ConvertImageCommand/948.
> > 2025-04-29T19:48:20.753303312Z magick: unable to open image `/images/temp/label.png': No such file or directory @ error/blob.c/OpenBlob/2924.
> > 2025-04-29T19:48:20.753330986Z magick: image sequence is required `+clone' @ error/convert.c/ConvertImageCommand/948.
> > 2025-04-29T19:48:20.885116370Z magick: unable to open image `/images/temp/shadowed_label.png': No such file or directory @ error/blob.c/OpenBlob/2924.
> > 2025-04-29T19:48:20.885142684Z magick: image sequence is required `-composite' @ error/mogrify.c/MogrifyImageList/8003.
> > 2025-04-29T19:48:20.885144695Z magick: no images defined `/images/temp/82991.jpg' @ error/convert.c/ConvertImageCommand/3229.
> > 2025-04-29T19:48:20.914276346Z 
> > 2025-04-29T19:48:20.924508381Z Deleted temporary file: /images/temp/82991.jpg
> > ```
> 
> Would you mind sharing how you've set up your docker compose? (Redacting API key, Plex token)

Installing on windows:
```
  maintainerr-overlay-helperr:
    image: gsariev/maintainerr-overlay-helperr:develop
    environment:
      PLEX_URL: "http://192.168.0.58:32400"
      PLEX_TOKEN: "**********"
      MAINTAINERR_URL: "http://192.168.0.58:6246"
      IMAGE_SAVE_PATH: "/images"
      ORIGINAL_IMAGE_PATH: "/images/originals"
      TEMP_IMAGE_PATH: "/images/temp"

      # Change the values here to customize the overlay
      FONT_PATH: "/fonts"
      FONT_COLOR: "#ffffff"
      BACK_COLOR: "#B20710"
      FONT_SIZE: "65"
      PADDING: "15"
      BACK_RADIUS: "20"
      HORIZONTAL_OFFSET: "80"
      HORIZONTAL_ALIGN: "center"
      VERTICAL_OFFSET: "40"
      VERTICAL_ALIGN: "bottom"

      BACK_WIDTH: "1500"    # Set your desired width in pixels
      BACK_HEIGHT: "100"    # Set your desired height in pixels
      DATE_FORMAT: "d MMM"    # Set your desired date format between "d MMM" or "MMM d"
      OVERLAY_TEXT: "Leaving: "    # Set your desired text to display before removal date
      FONT_NAME: "Roboto-Bold"    # Font file name with .ttf extension. Fonts available from /fonts directory. Added Kometa's and PATTRMM's ones for consistency if you're already using one or both of these tools.
      ENABLE_DAY_SUFFIX: true    # Enable or disable date suffix (i.e. th from November 14th). Mainly for french people
      ENABLE_UPPERCASE: true    # Use uppercase or lowercase for date format

      LANGUAGE: "en-GB"    # Used for date format and month abbreviation language. You can change this as needed (e.g., "fr-FR" for French), will default to en-US if not provided.

      RUN_INTERVAL: "2"    # Set the run interval to after X minutes; default is 480 minutes (8 hours) if not specified
    volumes:
      - /c/maintainerr-overlay-helper/images:/images
      - /c/maintainerr-overlay-helper/config/fonts:/fonts
    network_mode: "bridge"
```
