### ISSUE TITLE
Possible Re-Factor From PowerShell to a Linux Base Image

### ISSUE THREAD

**Issue by adjutantreflex** [gssariev/maintainerr-overlay-helperr#19]
I'm a docker novice so I may be misreading the codebase, but I noticed the main script is in PowerShell and runs on a PowerShell base image, though it then apt-get installs the required tools to do the actual image manipulation.

Do we think there's any possibility of refactoring the script into bash or another linux-based scripting language so we could use a minimal linux base image instead? I'm only asking because I noticed memory usage seems extremely high for this container. Dozzle reports to me that running this image is somehow consuming 985MB of RAM, somehow more than all five of my *arr containers combined. I'm presuming that's because of the hefty PowerShell base image and not the actual function/execution of the script.

Just wondering! Thanks

**Comment by adjutantreflex** [comment]
Ahhhh so maybe something about my particular setup.

I'm running the container on a simple Ubuntu LTS Server stack, with docker-compose. Nothing fancy by any means. Dozzle and  docker stats are reporting it's memory usage hovering continuously around 1GB.

`75414932a8e1   Maintainerr-Helper    0.00%     1.016GiB / 15.5GiB   6.56%   279MB / 2.37GB  400MB / 4.1GB`

Docker exec'ing into the container and running top shows the pwsh session is definitely the process using all the memory. That's about as deep as my troubleshooting ability can go on that front.

Restarting the container it started with about 100MB during initialization, fluctuated up to about 150MB during initial processing run and then interestingly jumped up to 325MB AFTER finishing. 

`75414932a8e1   Maintainerr-Helper    0.00%     325.9MiB / 15.5GiB   2.05%     1.61MB / 54.9MB   4.31MB / 90.1MB`

I'm using the default interval time of 8 hours, so perhaps there's something there where it jumps ~300MB each run but cleans up memory on a 24-hour basis?

Either way, great work man. I have this hooked up to a shared server and it is AMAZING to have everything being added by lists, rotated out with Maintainerr and tagged with this tool so there's a nice visual indicator.

**Comment by gssariev** [comment]
@adjutantreflex 

If you're feeling adventurous, you can try out the cron image: **gsariev/maintainerr-overlay-helperr:collection-reorder-cron**

It's still WIP, but with using cron instead of the while loop as is currently, Portainer reports that the container is using about **10 MB** of memory and it spikes up to about **140 MB** when the script is working before being suspended until the next run. Would be curious to see how things will look on your end, if you decide to try it out.

This build includes the following new variables that you should add to your docker-compose:

```yml
CRON_SCHEDULE: "0 */8 * * *" # Run the script every 8 hours
RUN_ON_CREATION: "false" # Set to true if you want the script to execute upon initial boot, or set to false if you want to have it triggered on the specified time
PLEX_COLLECTION_ORDER: "asc" # Re-order the collection based on deletion date; choose between ascending (asc ) or descending  (desc)
REORDER_COLLECTIONS: "Leaving Soon" # Name of the collection that should be reordered; you can include multiple collections separated by comma
```

New volume for cron log. You'll probably have to create an empty log file and point to it, if you run into a log-related error (using my Unraid setup as example)

```yml
- /mnt/user/appdata/maintainerr/logs/cron.log:/var/log/cron.log
```

Feedback is always appreciated!
